@host=http://localhost:5000

//Get DB
GET {{host}}/getDB

###

//Get all products
GET {{host}}/produits

###

//Get products by gender
GET {{host}}/produits/femme

###

//Get product by id
GET {{host}}/produit/1

###
